---
abstract: 'A Collection of Routines for validating and transforming strings'
author:
  - 'John Karr <brainbuz@brainbuz.org>'
build_requires:
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.140640'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: String-Validator
requires:
  perl: '5.008'
  strict: '0'
  warnings: '0'
version: '1.00'
